@baseUrl = http://localhost:8080
@email = j@j.com
@password = 123456

# @name login
POST {{baseUrl}}/api/login
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}

###

@token = {{login.response.body.$.accessToken}}

POST {{baseUrl}}/api/todos
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Buy groceries"
}

###

PUT {{baseUrl}}/api/todos/6190e553-207a-444f-80e3-433742767c43
Content-Type: application/json
Authorization: Bearer {{token}}

###

DELETE {{baseUrl}}/api/todos/6190e553-207a-444f-80e3-433742767c43
Authorization: Bearer {{token}}

###

GET {{baseUrl}}/api/todos?limit=10&page=2
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/api/todos/dc02bc68-e38d-4539-b8c6-ea2a608c3447
Authorization: Bearer {{token}}