@baseUrl = http://localhost:8080
@name = john doe
@email = j@j.com
@password = 123456

POST {{baseUrl}}/api/register
Content-Type: application/json

{
    "name": "{{name}}",
    "email": "{{email}}",
    "password": "{{password}}"
}

###

# @name login
POST {{baseUrl}}/api/login
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}

###

@token = {{login.response.body.$.accessToken}}